### ISSUE TITLE
[Meta] Implement triagebot commands for each step of our procedure

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team-prioritization#8]
This is a tracking issue about something that is still il-defined but the idea would be to split what we already have on https://github.com/rust-lang/triagebot/blob/master/src/bin/prioritization.rs into a set of things that can be executed using Zulip triagebot commands.

- [ ] Implement @triagebot commands for each step of our procedure
  - [ ] Unprioritized `I-prioritize` pending list
  - [ ] Unprioritized Regressions pending list
  - [ ] Nominations pending list
  - [ ] PRs waiting on team pending list
  - [ ] Agenda
    - [ ] Render MCP section only
    - [ ] Render Beta nominations only
    - [ ] Render Stable nominations only
    - [ ] Render PRs waiting on team only
    - [ ] Render Issues of note short summary only
    - [ ] Render Issues of note P-critical only
    - [ ] Render Issues of note Unassigned P-high regressions only
    - [ ] Render Nominated Issues only
    - [ ] Render the full agenda
  - [ ] Announcements
  - [ ] Toolstate
  - [ ] Performance regressions

Leaving this as is for now but we should be defining how the command should look like for each section and what would each command return.

**Comment by spastorino** [comment]
When implementing part of this we can put back parts of the code removed in https://github.com/rust-lang/triagebot/pull/738 and https://github.com/rust-lang/triagebot/pull/739

**Comment by apiraino** [comment]
We settled since long on a workflow with the whole agenda on a single file and we copy and paste from that. Seems more efficient and less prone to networks hiccups
